<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-MIAPP68" failures="1" tests="1" name="runners.TestNGRunner" time="22.121" errors="0" timestamp="2023-12-11T11:01:45 IST" skipped="0">
  <testcase classname="runners.TestNGRunner" name="runScenario" time="22.121">
    <failure message="expected [https://www.chilternoakfurniture.co.uk/account/login?return_url=%2Faccount] but found [https://www.chilternoakfurniture.co.uk/challenge]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://www.chilternoakfurniture.co.uk/account/login?return_url=%2Faccount] but found [https://www.chilternoakfurniture.co.uk/challenge]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at stepDefinitions.SignInStepDef.i_click_on_sign_in_button(SignInStepDef.java:71)
at âœ½.I click on Sign In button(file:///C:/Users/hp/eclipse-workspace/RLLproject/src/test/java/features/SignIn.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- runners.TestNGRunner -->
